### ISSUE TITLE
Tool ain't working 

### ISSUE THREAD

**Issue by bobaikato** [ASChampOmega/ResumeReader#1]
Was looking for a tool similar to yours, but I did try your solution, it doesn't work.

![image](https://user-images.githubusercontent.com/14136806/134784368-c61af2f7-5009-4032-a670-4b1053195fa0.png)

` No Background found :( `
`No Skill Found :(`

**Comment by ASChampOmega** [comment]
Hi!

From the screenshot, I see that you have not input 1, 2, 3. If you don't input 2, then you won't be able to run 3 properly, and you won't get any skills either.

About the background: The software finds it difficult to read very complex resumes (such as those with a lot of graphics). This is because the PDF reader library that I used is not the best. So it misses out a lot of text for complex resumes. 

I'm trying to work that out on my end, and haven't put it in the colab notebook yet.

If you could share the resume you used to test my product, maybe I could check it out on my end.
